FROM registry.redhat.io/rhel9/rhel-bootc:9.5-1742917433
#RUN dnf -y update && dnf -y install tmux mkpasswd vim git tree
RUN dnf -y install tmux mkpasswd vim git tree
RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel bootc-user -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
RUN dnf -y install httpd && \
    systemctl enable httpd && \
    mv /var/www /usr/share/www && \
    sed -ie 's,/var/www,/usr/share/www,' /etc/httpd/conf/httpd.conf

RUN dnf -y install rhc cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    dnf clean all

RUN dnf -y upgrade --cve="CVE-2025-21785,CVE-2025-22869" 
    
RUN echo "Welcome to the mind-blowing ANZ demo bootc-http instance!" > /usr/share/www/html/index.html

# Register system at first boot, as per:
# https://gitlab.com/fedora/bootc/examples/-/blob/main/insights/Containerfile?ref_type=heads
COPY files/rhc-connect.service /usr/lib/systemd/system/rhc-connect.service
COPY files/.rhc_connect_credentials /etc/rhc/.rhc_connect_credentials
RUN systemctl enable rhc-connect && touch /etc/rhc/.run_rhc_connect_next_boot

EXPOSE 80
