FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS builder

LABEL org.opencontainers.image.description="Container Disk image for qcow2 VM image to be used with OpenShift Virtualization"
LABEL org.opencontainers.image.authors="Benjamin Blasco"

ADD --chown=107:107 output/disk.qcow2 /disk/
RUN chmod 0440 /disk/*
FROM scratch
COPY --from=builder /disk/* /disk/
